#数据库配置
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
#连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

#解禁所有endpoint
management:
  endpoints:
    web:
      exposure:
        include: beans,health